import type { PredefinedNote, Season } from "./types";

export const seasons: { value: Season; label: string }[] = [
  { value: "spring", label: "🌸 Vår" },
  { value: "summer", label: "☀️ Sommar" },
  { value: "autumn", label: "🍂 Höst" },
  { value: "winter", label: "❄️ Vinter" },
  { value: "all_year", label: "🌍 Året runt" },
];

export const fallbackCountries = [
  "Sverige",
  "Norge",
  "Danmark",
  "Finland",
  "Island",
  "Tyskland",
  "Frankrike",
  "Spanien",
  "Italien",
  "Nederländerna",
  "Belgien",
  "Polen",
  "Storbritannien",
  "USA",
  "Kanada",
  "Australien",
  "Japan",
  "Sydkorea",
  "Förenade Arabemiraten",
  "Saudiarabien",
];

export const predefinedNotes: PredefinedNote[] = [
  { label: "Bergamott", emoji: "🍋" },
  { label: "Citron", emoji: "🍋" },
  { label: "Grapefrukt", emoji: "🍊" },
  { label: "Apelsinblom", emoji: "🌼" },
  { label: "Neroli", emoji: "🌿" },
  { label: "Lavendel", emoji: "🪻" },
  { label: "Ros", emoji: "🌹" },
  { label: "Jasmin", emoji: "🌸" },
  { label: "Ylang-ylang", emoji: "🌺" },
  { label: "Iris", emoji: "🌷" },
  { label: "Viol", emoji: "💜" },
  { label: "Muguet", emoji: "🌼" },
  { label: "Kardemumma", emoji: "🫚" },
  { label: "Kanel", emoji: "🪵" },
  { label: "Saffran", emoji: "🧡" },
  { label: "Peppar", emoji: "🌶️" },
  { label: "Ingefära", emoji: "🫚" },
  { label: "Muskot", emoji: "🌰" },
  { label: "Vanilj", emoji: "🍦" },
  { label: "Tonkabona", emoji: "🫘" },
  { label: "Barnsten", emoji: "🟠" },
  { label: "Mysk", emoji: "🫧" },
  { label: "Sandelträ", emoji: "🪵" },
  { label: "Ceder", emoji: "🌲" },
  { label: "Vetiver", emoji: "🌱" },
  { label: "Patchouli", emoji: "🍃" },
  { label: "Oud", emoji: "🪵" },
  { label: "Rökelse", emoji: "🕯️" },
  { label: "Läder", emoji: "🧥" },
  { label: "Kokos", emoji: "🥥" },
];
